### PR TITLE
Aadejare Patch 

### PR DESCRIPTION
**Pull request by aadejare**
Updated to include gamer tag via name tag, gender, pronouns, and main language for personal information.  Includes entrantTeam to acknowledge if they are in a team  battle (multiple entrants coming together to play against multiple entrants)

### CODE REVIEW

**Comment by VestboyMyst** [comment]
Does it make more sense to change `mainLanguage` to `nationality` ? 
Could you explain a bit more about the context for how these fields will be used, is it a stream overlay?

**Comment by aadejare** [comment]
Good point, to demonstrate the scenario let's use Canada:
Canada is someone's nationality.  Someone from Canada can have a main language of English, but if they're from Quebec it can be French.
So you can see the following scenario:
Nationality: 'CAN'
mainLanugage: 'French'

OR 
Nationality: 'CAN'
mainLanugage: 'English'

It's to allow for flexibility for those who want to speak.  It may not be a  necessary field, but it can allow for people to pull up speaking info later.

**Comment by aadejare** [comment]
Went back and corrected issues.

**Comment by aadejare** [comment]
> This PR might do from a better name for a versioning & merge perspective? I got the notification for this PR but had no idea what this was meant to be.

Yes, and I appreciate it will do that in the future.

```
Adding language is complex - and gets to a question of what is a User, a Participant, or an Entrant in a specific event. A team wouldn't have a language set on it, in most cases, but also more importantly:
Why, from a bracket ORM perspective, do you care what language a specific Entrant speaks in all conditions? This should at minimum be optional, but frankly doesn't seem like it is an essential part of a bracket. User experience, certainly. Data pulling, likely. But what does it tell someone looking at the bracket in all cases? It doesn't say how to address them like pronouns and the other fields do (the TO/viewer/commentator will communicate in their own language how to address the player(s)).
```

So it could be an optional /conditional field and not required.  From a more philosophical approach: I assume that people will run a tournament every single day with multiple languages and multiple countries/nationalities.   Having these language settings as a option (thus shifting away from mainLanguage) can allow other applications to render the data appropriately and handle different players data pronoucinations etc.  

`This seems like it goes beyond the scope of a bracket format and more to a general data ORM. I worry about scope creep with the bracket overall, to be honest.
`
This is a fair thought.  I did too. My philosophy was to contribute ways to make the standard more open to different people in different scenarios (thinking language, gender, race, etc) at the expense of a bit of complication. That's why it seems like I was jumping the gun with a lot of new stuff.

**Comment by EddieDemon** [comment]
To be completely open minded:

- Gender should be plural and an array (or at least multi-typed.)
- Pronouns should be an array (or at least multi-typed.)
- Language should be plural and an array (or at least multi-typed.)
   - Where the index determines the preference (should be documented)
      - Or it should be a dictionary/hash table so the order of element don't depict preference.
- Value of `entrantTeam.minLenth` is invalid. Probably the property you're searching for is `required` ?

Bare in mind that multi-typing isn't supported in A LOT of languages and it will default to arrays.

**Comment by aadejare** [comment]
> 

I think that will need to be discussed if we want to put in mutl-typing or if we want to push for the array (as it's most readable).

**Comment by VestboyMyst** [comment]
leaving this branch open for continued discussion

**Comment by aadejare** [comment]
I closed patch to reconcile with recent updates including suggestions given by the above members

**Pull request closed without merging**
